### ISSUE TITLE
Do you do this in addition to cpanel backups?

### ISSUE THREAD

**Issue by MACscr** [celesteking/cpanel-backup#1]
Do you use this in an addition to the normal cpanel backups? I mean, it would be needed in order to restore a full account, right? If so, what benefit does bacula add on top of this?

**Comment by celesteking** [comment]
No additional benefits.

**Comment by MACscr** [comment]
Im confused. Why would you be using it then? I can't stand the cpanel backup methods, but in order for the ability to restore actual accounts versus just raw data, it's required, right?

**Comment by celesteking** [comment]
Nope, it's not required. If you don't understand the idea of this software, don't use it.
